[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'ffmpeg']

[phases.install]
cmds = ['npm install --legacy-peer-deps --no-audit --omit=optional']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
