[phases.setup]
nixPkgs = ['nodejs_20', 'ffmpeg']

[phases.install]
cmds = [
  'npm pkg delete optionalDependencies',
  'npm install --legacy-peer-deps --no-optional'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
